from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime

class CustomerRequest(BaseModel):
    customer_id: Optional[int] = None  # Auto-generated by DB
    user_id: int
    name: str
    phone: Optional[str] = None
    email: Optional[EmailStr] = None
    address: Optional[str] = None
    created_at: Optional[str] = None  # Auto-generated in API
