from pydantic import BaseModel
from typing import Optional

class PaymentRequest(BaseModel):
    payment_id: Optional[int] = None  # Auto-generated by DB
    old_sale_id: Optional[int] = None
    payment_date: str
    amount: float
    payment_method: str
    notes: Optional[str] = None
    created_by_user_id: int
    user_id: int
    purchase_id: Optional[int] = None
    expense_id: Optional[int] = None
    transaction_date: Optional[str] = None
    sale_log_id: Optional[int] = None
    sale_history_id: Optional[int] = None
    sale_id: Optional[int] = None
