from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime

class UserRequest(BaseModel):
    user_id: Optional[int] = None  # Auto-generated by DB
    username: str
    email: EmailStr
    password_hash: str  # Store hashed password
    role: str
    created_at: Optional[str] = None  # Auto-generated in API
    plan: Optional[str] = "free"
    is_verified: Optional[bool] = False
    verification_token: Optional[str] = None
    deleted: Optional[bool] = False
    logo_url: Optional[str] = None
    account_number: Optional[str] = None
    bank_name: Optional[str] = None
    access_code: Optional[str] = None
    avatar_url: Optional[str] = None
    phone_number: Optional[str] = None
    address: Optional[str] = None
    tenant_name: Optional[str] = None
